### ISSUE TITLE
How About Adding a search_data() Function? 🤔

### ISSUE THREAD

**Issue by djibyko** [codingtuto/LiteJsonDb#2]
Hey folks,

Loving the new updates to LiteJsonDb—you guys are killing it! Just had a thought: it’d be awesome to have a search_data() function in the mix.

Here’s what I’m thinking:

    Basic Search: search_data(x) - This would look for the value x anywhere in the data.
    Key-specific Search: search_data(x, in key) - This would search for x specifically within the specified key.

It’d make finding stuff way easier and save a lot of time. What do you think?

**Comment by codingtuto** [comment]
Wow that's a good suggestion I will integrate it as soon as possible in the new version that will arrive.

**Comment by codingtuto** [comment]
Done we added it .
